/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.format.DateTimeFormatter;
import model.ControleDeValores;
import model.Despesa;
import model.LeituraDeDados;
import model.Receita;
import model.ValoresDomesticos;

/**
 *
 * @author Gabriel Krzizanowski
 */
public class Extrato extends javax.swing.JDialog {

    /**
     * Creates new form Extrato
     */
    public Extrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        montarReceitas();
    }

    public void montarReceitas() {
        Double totalExtrato = 0.0;
        LeituraDeDados leituraDeDados = new LeituraDeDados();
        String descricao = "";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (ValoresDomesticos valoresDomesticos : leituraDeDados.extratoFile()) {

            if (valoresDomesticos instanceof Despesa) {
                Despesa despesa = (Despesa) valoresDomesticos;
                String hojeFormatado = despesa.getDia().format(formatter);
                descricao += "\nDescrição: " + despesa.getDescricao() + "\nValor: - " + despesa.getValor() + "\nDia: " + hojeFormatado + "\n------------------";
            } else {
                Receita receita = (Receita) valoresDomesticos;
                String hojeFormatado = receita.getDia().format(formatter);
                descricao += "\nDescrição: " + receita.getDescricao() + "\nValor: + " + receita.getValor() + "\nDia: " + hojeFormatado + "\n------------------";
            }
        }

        for (ValoresDomesticos valoresDomesticos : leituraDeDados.extratoFile()) {
            if (valoresDomesticos instanceof Despesa) {
                totalExtrato -= ((Despesa) valoresDomesticos).getValor();

            } else if (valoresDomesticos instanceof Receita) {
                totalExtrato += ((Receita) valoresDomesticos).getValor();
            }

        }
        String receita = "\nTotal do Extrato: " + totalExtrato;
        taExtrato.append(descricao);
        taExtrato.append(receita);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taExtrato = new javax.swing.JTextArea();
        btOrdenar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taExtrato.setColumns(20);
        taExtrato.setRows(5);
        jScrollPane1.setViewportView(taExtrato);

        btOrdenar.setText("Ordenar por data");

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFechar)
                    .addComponent(btOrdenar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        
        Extrato.this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Extrato dialog = new Extrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taExtrato;
    // End of variables declaration//GEN-END:variables
}
